version: "3"

services:
    app:
        environment:
            VIRTUAL_HOST: $HOSTNAME
            VIRTUAL_PORT: 9000
            LETSENCRYPT_HOST: $HOSTNAME

networks:
    default:
        external:
            name: nginx-proxy