version: "3"

services:
    app:
        environment:
            MINIO_SERVER_URL: ${HOSTNAME}
            VIRTUAL_HOST: ${HOSTNAME}:9000,${CONSOLE_HOSTNAME}:9001
            LETSENCRYPT_HOST: ${HOSTNAME},${CONSOLE_HOSTNAME}

networks:
    default:
        external:
            name: nginx-proxy
