version: "3"

services:
    app:
        image: minio/minio
        environment:
            MINIO_ROOT_USER: ${ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${SECRET_KEY}
        volumes:
            - data:/data:rw
        command: server /data

volumes:
    data: